### ISSUE TITLE
Replace `tui` wiith `ratatui`

### ISSUE THREAD

**Issue by auronandace** [ulyssa/modalkit#105]
Not sure if you are aware but tui has not been maintained for quite some time now.

There is a new active fork of the project: https://github.com/tui-rs-revival/ratatui

Just wanted to make you aware of it in case you would like to switch to it.

**Comment by ulyssa** [comment]
I was unaware of the fork. Thanks for mentioning it! I implemented most of my own widgets, so my usage of the library is pretty straightforward, but the `const` functions for `Style` and others seem like a nice addition.
